export { default as ERPDashboard } from './ERPDashboard';
export { default as AccountingGeneral } from './AccountingGeneral';
export { default as PurchaseManagement } from './PurchaseManagement';
export { default as SalesInvoicing } from './SalesInvoicing';
export { default as InventoryControl } from './InventoryControl';
export { default as ProductionPlanning } from './ProductionPlanning';
export { default as ProjectCosting } from './ProjectCosting';
export { default as TreasuryManagement } from './TreasuryManagement';
export { default as FinancialReporting } from './FinancialReporting';
