export const OPPORTUNITY_STAGES = {
  PROSPECTO: 'prospecto',
  CALIFICACION: 'calificacion',
  PROPUESTA: 'propuesta',
  NEGOCIACION: 'negociacion',
  GANADA: 'ganada',
  PERDIDA: 'perdida',
};

export const OPPORTUNITY_STAGE_LABELS = {
  [OPPORTUNITY_STAGES.PROSPECTO]: 'Prospecto',
  [OPPORTUNITY_STAGES.CALIFICACION]: 'Calificación',
  [OPPORTUNITY_STAGES.PROPUESTA]: 'Propuesta',
  [OPPORTUNITY_STAGES.NEGOCIACION]: 'Negociación',
  [OPPORTUNITY_STAGES.GANADA]: 'Ganada',
  [OPPORTUNITY_STAGES.PERDIDA]: 'Perdida',
};

export const OPPORTUNITY_STAGE_COLORS = {
  [OPPORTUNITY_STAGES.PROSPECTO]: 'secondary',
  [OPPORTUNITY_STAGES.CALIFICACION]: 'info',
  [OPPORTUNITY_STAGES.PROPUESTA]: 'warning',
  [OPPORTUNITY_STAGES.NEGOCIACION]: 'primary',
  [OPPORTUNITY_STAGES.GANADA]: 'success',
  [OPPORTUNITY_STAGES.PERDIDA]: 'error',
};

export const OPPORTUNITY_STAGE_PROBABILITIES = {
  [OPPORTUNITY_STAGES.PROSPECTO]: 10,
  [OPPORTUNITY_STAGES.CALIFICACION]: 25,
  [OPPORTUNITY_STAGES.PROPUESTA]: 50,
  [OPPORTUNITY_STAGES.NEGOCIACION]: 75,
  [OPPORTUNITY_STAGES.GANADA]: 100,
  [OPPORTUNITY_STAGES.PERDIDA]: 0,
};

export const OPPORTUNITY_PRIORITIES = {
  BAJA: 'baja',
  MEDIA: 'media',
  ALTA: 'alta',
  CRITICA: 'critica',
};

export const OPPORTUNITY_PRIORITY_LABELS = {
  [OPPORTUNITY_PRIORITIES.BAJA]: 'Baja',
  [OPPORTUNITY_PRIORITIES.MEDIA]: 'Media',
  [OPPORTUNITY_PRIORITIES.ALTA]: 'Alta',
  [OPPORTUNITY_PRIORITIES.CRITICA]: 'Crítica',
};

export const OPPORTUNITY_PRIORITY_COLORS = {
  [OPPORTUNITY_PRIORITIES.BAJA]: 'default',
  [OPPORTUNITY_PRIORITIES.MEDIA]: 'info',
  [OPPORTUNITY_PRIORITIES.ALTA]: 'warning',
  [OPPORTUNITY_PRIORITIES.CRITICA]: 'error',
};
